android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Override this when building:
# gradle assembleDebug -PWEBAPP_URL=https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec
WEBAPP_URL=https://script.google.com/macros/s/REPLACE_WITH_DEPLOYMENT_ID/exec
